import React from 'react';
import { EditorState } from 'draft-js';

const WritualContext = React.createContext({
  _addScene: () => {},
  activeDetail: undefined,
  addChar: () => {},
  addCharacter: undefined,
  addEp: () => {},
  addEpisode: undefined, 
  addProj: () => {},
  addProject: undefined, 
  addScene: undefined, 
  author: {},
  bottleEpisode: undefined, 
  budget:{}, 
  charAge: {},
  charGender: {},
  charName: {},
  closeAddChar: () => {},
  closeAddEp: () => {},
  closeAddProj: () => {},
  closeAddScene: () => {},
  closeChatWindow: () => {},
  closeShareComponent: () => {},
  collapseProjectList: () => {},
  collapseSharedProjectList: () => {},
  collapseSharedTvList: () => {},
  collapseTvShowList: () => {},
  createUnreadArgs: () => {},
  current_project_id: undefined, 
  currentAct: undefined, 
  currentActInstruction: undefined,
  currentActOneStep: undefined,
  currentActThreeStep: undefined,
  currentActTwoStep: undefined,
  currentAttribute: undefined,
  currentChar: undefined, 
  currentEpisode: undefined,
  currentEpisodeTitle: undefined, 
  currentProj: undefined,
  currentProjFormat: undefined, 
  currentTab: undefined,
  currentUserProjectShared: undefined, 
  deleteChar: () => {},
  deleteProj: () => {},
  deleteSceneMode: () => {},
  deleteScenes: undefined, 
  detailContent: undefined, 
  displayName: undefined,
  editorState: EditorState.createEmpty(),
  email: undefined,
  episode_title: undefined,
  episodes: undefined, 
  episode_id: undefined, 
  episodeSelected: () => {},
  expandProjectList: () => {},
  expandSharedProjectList: () => {},
  expandSharedTvList: () => {},
  expandTvShowList: () => {},
  framework: {},
  genre: {},
  getAllUserProjects: () => {},
  getAuthToken: () => {},
  getChatIconUrls: () => {},
  getEditorState: () => {},
  getEpisodes: () => {},
  getProjectScenes: () => {},
  getSteps: () => {},
  getUnread: () => {},
  goHome: () => {},
  handCharUpdateAge: () => {},
  handCharUpdateGender: () => {},
  handCharUpdateName: () => {}, 
  handleActOneStepClick: () => {},
  handleActThreeStepClick: () => {},
  handleActTwoStepClick: () => {},
  handleAddCharFormReset: () => {},
  handleAddCharFormSubmit: () => {},
  handleAddSceneSubmit: () => {},
  handleEpFormSubmit: () => {},
  handleFormReset: () => {},
  handleFormSubmit: () => {},
  handleGoogleLogin: () => {},
  handleLandingClick: () => {},
  handleSearchUpdate: () => {},
  handleSignout: () => {},
  handleUpdateAuthor: () => {},
  handleUpdateBottle: () => {},
  handleUpdateBudget: () => {},
  handleUpdateCharAge: () => {},
  handleUpdateCharGender: () => {},
  handleUpdateCharName: () => {},
  handleUpdateFormat: () => {},
  handleUpdateGenre: () => {},
  handleUpdateLogline: () => {},
  handleUpdateSimilarProjects: () => {},
  handleUpdateTimePeriod: () => {},
  handleUpdateTitle: () => {},
  handleUserImgClick: () => {},
  hideEpisode: () => {},
  hideProj: () => {},
  history: undefined, 
  idToken: undefined, 
  isEpisode: undefined, 
  logline: {},
  numUnreadMsgs: undefined,
  onAttributeClick: () => {},
  onCharacterClick: () => {},
  onProjectClick: () => {},
  onSelectedItemsChange: () => {},
  onTabClick: () => {},
  openChats: undefined, 
  openUserChat: () => {},
  photoUrl: undefined,
  photoUrl: undefined,
  photoUrls: undefined,
  projCharacters: undefined,
  projectFormError: undefined,
  projectFormErrorField: undefined,
  projectFormErrorMsg: undefined,
  projectHidden: undefined,
  projects: undefined,
  projectToShare: undefined, 
  projformat: {},
  projScenes: undefined, 
  projTitles: undefined, 
  renderProfileMenu: false,
  renderShareComponent: undefined,
  renderSharedUpArrow: undefined,
  renderUpArrow: undefined,
  renderUpTvArrow: undefined, 
  renderUpTvArrowShared: undefined,
  selectedEpisode: undefined,
  selectedItems: undefined, 
  sharedEpisodes: undefined, 
  sharedProjClicked: undefined, 
  sharedProjectClicked: undefined, 
  sharedProjectHidden: undefined,
  sharedProjects: undefined, 
  sharedWith: undefined,   
  shareProject: () => {},
  showHiddenEpisodes: () => {},
  showHiddenMode: undefined,
  showHiddenModeShared: undefined,
  showHiddenProjects: () => {},
  showHiddenSharedEpisodes: () => {},
  showHiddenSharedProjects: () => {},
  showShareProject: () => {},
  signInWithGoogle: () => {},
  signOut: () => {},
  similarepisodes: {},
  simimlarprojects: {}, 
  steps: '',
  tableName: undefined,
  tableName: undefined,
  tabSelectBorderColor: undefined,
  tabSelectBorderWidth: undefined,
  tabTitles: undefined,
  timeperiod: {}, 
  title: {},
  tvArrowProj: undefined, 
  uid: undefined,
  unHideEpisode: () => {}, 
  unHideProj: () => {},
  unreadMessages: undefined,
  unreadMessagesStatus: [],
  unreadMsgs: undefined,
  updateCharacterDetail: {},
  updateProjectTreatment: () => {},
  updateFeedback: () => {},
  updateUser: () => {},
  userAccount: null,
  validateAuthorName: () => {},
  validateFormatName: () => {},
  validateGenreName: () => {},
  validateLoglineVal: () => {},
  validateTitleName: () => {},
  windowHeight: undefined,
  windowWidth: undefined, 
  
});

export default WritualContext;
